language: scala

scala:
  - 2.11.12
  - 2.12.8
  - 2.13.0-M5

services:
  - docker

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sbt
    - $HOME/.ivy2

jdk:
  - oraclejdk8

before_script:
  # For DynamoDB
  - export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$HOME/.ivy2/cache/com.almworks.sqlite4java/libsqlite4java-linux-amd64/sos"

script:
  ## This runs the template with the default parameters, and runs test within the templated app.
  - sbt -Dfile.encoding=UTF8 -J-XX:ReservedCodeCacheSize=256M test

  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm